spring:
  application:
    name: voluntar

  profiles:
    active: test

  graphql:
    graphiql:
      enabled: true

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 150MB

  mongodb:
    username: ${MONGO_USERNAME:volunteer_be}
    password: ${MONGO_PASSWORD}
    database: volunteer_db_test
    uri: mongodb+srv://${spring.mongodb.username}:${spring.mongodb.password}@cluster0.zgo27k9.mongodb.net/${spring.mongodb.database}?retryWrites=true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://volunteer-kc.duckdns.org/realms/volunteer
  mail:
    sender: amanemisalovereaddeathnote@gmail.com
    host: smtp-relay.brevo.com
    port: 587
    username: b97278001@smtp-brevo.com
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: templates/i18n/messages
    encoding: UTF-8

server:
  port: 8081

management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always   # TEMPORARY for debugging, change to when-authorized after

users:
  credentials:
    - username: admin
      password: password123
      roles: ADMIN

    - username: moderator
      password: password123
      roles: MODERATOR

    - username: volunteer
      password: password123
      roles: VOLUNTEER

    - username: ngo
      password: password123
      roles: NGO

google:
  drive:
    application-name: volunteer-platform
#    root-folder-id: ${GOOGLE_DRIVE_ROOT_FOLDER_ID}
    credentials-path: ${GOOGLE_DRIVE_CREDENTIALS_PATH}
    tokens-path: ${GOOGLE_DRIVE_TOKENS_PATH}

volunteer:
  volunteerPresenceConfirmationUlr: https://volunteer-fe.amanemisalovereaddeathnote.workers.dev/?eventId=%s&userId=%s
