spring:
  application:
    name: voluntar

  profiles:
    active: test

  graphql:
    graphiql:
      enabled: true

  mongodb:
    username: ${MONGO_USERNAME:volunteer_be}
    password: ${MONGO_PASSWORD}
    database: volunteer_db_test
    uri: mongodb+srv://${spring.mongodb.username}:${spring.mongodb.password}@cluster0.zgo27k9.mongodb.net/${spring.mongodb.database}?retryWrites=true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://volunteer-kc.duckdns.org/realms/volunteer
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: b97278001@smtp-brevo.com
    password: ${BREVO_SMTP_KEY}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n/messages
    encoding: UTF-8

server:
  port: 8081

management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always   # TEMPORARY for debugging, change to when-authorized after

users:
  credentials:
    - username: admin
      password: password123
      roles: USER

    - username: notadmin
      password: password123
      roles: ADNIN

google:
  drive:
    application-name: volunteer-platform
#    root-folder-id: ${GOOGLE_DRIVE_ROOT_FOLDER_ID}
    credentials-path: ${GOOGLE_DRIVE_CREDENTIALS_PATH:./config/google/credentials.json}
    tokens-path: ${GOOGLE_DRIVE_TOKENS_PATH:./config/google/tokens}

volunteer:
  volunteerPresenceConfirmationUlr: https://volunteer-fe.amanemisalovereaddeathnote.workers.dev/?eventId=%s&userId=%s
