spring:
  application:
    name: voluntar

  profiles:
    active: test

  graphql:
    graphiql:
      enabled: true

  mongodb:
    username: volunteer_be
    password: taSudhu6K_VLw
    database: volunteer_db_test
    uri: mongodb+srv://${spring.mongodb.username}:${spring.mongodb.password}@cluster0.zgo27k9.mongodb.net/${spring.mongodb.database}?retryWrites=true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://volunteer-kc.duckdns.org/realms/volunteer
  mail:
    host: ://gmail.com
    port: 587
    username: replace me
    password: replace me
  messages:
    basename: i18n/messages
    encoding: UTF-8
server:
  port: 8081

users:
  credentials:
    - username: admin
      password: password123
      roles: USER

    - username: notadmin
      password: password123
      roles: ADNIN
volunteer:
  volunteerPresenceConfirmationUlr: https://volunteer-fe.amanemisalovereaddeathnote.workers.dev/?eventId=%s&userId=%s


